name: auto_translator
description: A command-line tool to translate ARB files using cloud translation services.
version: 2.3.3
homepage: https://github.com/theLee3/flutter_auto_translator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  http: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.5
  lints: ^2.1.1
  mockito: ^5.4.2
  path: ^1.8.3
  test: ^1.24.3
